db:
  build: .
  container_name: gqlgen
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: gqlgen
  ports:
    - "3306:3306"