// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_todos

type NewTodo struct {
	Title  string `json:"title"`
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
